using System.Collections.Concurrent;
using System.Text.Json;
using Microsoft.Web.WebView2.Core;
using Microsoft.Web.WebView2.WinForms;

/// <summary>
/// Maintains the WebRTC leg required by stock Codex app-server when the user is
/// authenticated with ChatGPT OAuth. Chromium/WebView2 owns the RTCPeerConnection
/// so the SDP is generated by the same browser WebRTC stack expected by Codex.
/// Android audio still travels through app-server sideband appendAudio/outputAudio.
/// </summary>
internal sealed class CodexOAuthWebRtcPeer : IDisposable
{
    readonly object sync = new();
    readonly ConcurrentDictionary<long, TaskCompletionSource<string>> pending = new();
    readonly TaskCompletionSource<bool> ready = new(TaskCreationOptions.RunContinuationsAsynchronously);

    Thread? uiThread;
    Form? hostForm;
    WebView2? webView;
    long requestId;
    bool disposed;

    const string BridgePage = """
<!doctype html>
<html>
<body>
<script>
(() => {
  let pc = null;
  let dc = null;

  function post(obj) {
    window.chrome.webview.postMessage(JSON.stringify(obj));
  }

  function event(name, value) {
    post({ event: name, value: String(value ?? '') });
  }

  async function waitForIceGathering(peer, timeoutMs = 2500) {
    if (peer.iceGatheringState === 'complete') return;
    await Promise.race([
      new Promise(resolve => {
        const changed = () => {
          if (peer.iceGatheringState === 'complete') {
            peer.removeEventListener('icegatheringstatechange', changed);
            resolve();
          }
        };
        peer.addEventListener('icegatheringstatechange', changed);
      }),
      new Promise(resolve => setTimeout(resolve, timeoutMs))
    ]);
  }

  function closeCurrent(reason) {
    try { if (dc) dc.close(); } catch (_) {}
    try { if (pc) pc.close(); } catch (_) {}
    dc = null;
    pc = null;
    event('closed', reason || 'normal');
  }

  window.codexPeer = {
    async createOffer(id) {
      try {
        closeCurrent('replaced');
        pc = new RTCPeerConnection();
        pc.addTransceiver('audio', { direction: 'sendrecv' });
        dc = pc.createDataChannel('oai-events');

        dc.onopen = () => event('datachannel', 'open');
        dc.onclose = () => event('datachannel', 'closed');
        pc.onconnectionstatechange = () => event('connection', pc.connectionState);
        pc.oniceconnectionstatechange = () => event('ice', pc.iceConnectionState);
        pc.onicegatheringstatechange = () => event('ice-gathering', pc.iceGatheringState);

        const offer = await pc.createOffer();
        await pc.setLocalDescription(offer);
        await waitForIceGathering(pc);

        if (!pc.localDescription || !pc.localDescription.sdp)
          throw new Error('Chromium did not produce a local SDP offer.');

        post({ id, ok: true, result: pc.localDescription.sdp });
      } catch (e) {
        post({ id, ok: false, error: String(e && e.stack ? e.stack : e) });
      }
    },

    async applyAnswer(id, sdp) {
      try {
        if (!pc) throw new Error('WebRTC offer has not been created.');
        await pc.setRemoteDescription({ type: 'answer', sdp });
        post({ id, ok: true, result: 'ok' });
      } catch (e) {
        post({ id, ok: false, error: String(e && e.stack ? e.stack : e) });
      }
    },

    closePeer(id, reason) {
      try {
        closeCurrent(reason || 'normal');
        if (id) post({ id, ok: true, result: 'ok' });
      } catch (e) {
        if (id) post({ id, ok: false, error: String(e) });
      }
    }
  };

  post({ event: 'bridge-ready', value: navigator.userAgent });
})();
</script>
</body>
</html>
""";

    public async Task<string> CreateOfferAsync()
    {
        ThrowIfDisposed();
        await EnsureHostAsync();
        Console.WriteLine("Codex OAuth WebRTC: creating Chromium offer");
        return await InvokeAsync("createOffer");
    }

    public async Task ApplyAnswerAsync(string sdp)
    {
        ThrowIfDisposed();
        if (string.IsNullOrWhiteSpace(sdp))
            throw new ArgumentException("SDP answer is empty.", nameof(sdp));
        await EnsureHostAsync();
        await InvokeAsync("applyAnswer", sdp);
    }

    public void Close(string reason = "normal")
    {
        if (disposed || !ready.Task.IsCompletedSuccessfully) return;
        _ = InvokeAsync("closePeer", reason).ContinueWith(_ => { }, TaskScheduler.Default);
    }

    async Task EnsureHostAsync()
    {
        lock (sync)
        {
            if (uiThread is null)
            {
                uiThread = new Thread(UiThreadMain)
                {
                    IsBackground = true,
                    Name = "Codex Chromium WebRTC"
                };
                uiThread.SetApartmentState(ApartmentState.STA);
                uiThread.Start();
            }
        }

        await ready.Task.WaitAsync(TimeSpan.FromSeconds(15));
    }

    void UiThreadMain()
    {
        try
        {
            var form = new Form
            {
                Text = "Codex Chromium WebRTC",
                ShowInTaskbar = false,
                FormBorderStyle = FormBorderStyle.FixedToolWindow,
                StartPosition = FormStartPosition.Manual,
                Location = new Point(-32000, -32000),
                Size = new Size(2, 2),
                Opacity = 0
            };
            var view = new WebView2 { Dock = DockStyle.Fill };
            form.Controls.Add(view);
            hostForm = form;
            webView = view;

            form.Load += async (_, _) =>
            {
                try
                {
                    await view.EnsureCoreWebView2Async();
                    view.CoreWebView2.Settings.AreDefaultContextMenusEnabled = false;
                    view.CoreWebView2.Settings.AreDevToolsEnabled = false;
                    view.CoreWebView2.Settings.IsStatusBarEnabled = false;
                    view.CoreWebView2.WebMessageReceived += OnWebMessageReceived;

                    var navigation = new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);
                    void Completed(object? sender, CoreWebView2NavigationCompletedEventArgs args)
                    {
                        view.NavigationCompleted -= Completed;
                        if (args.IsSuccess) navigation.TrySetResult(true);
                        else navigation.TrySetException(new InvalidOperationException("WebView2 bridge page failed to load: " + args.WebErrorStatus));
                    }
                    view.NavigationCompleted += Completed;
                    view.NavigateToString(BridgePage);
                    await navigation.Task.WaitAsync(TimeSpan.FromSeconds(10));
                    ready.TrySetResult(true);
                    Console.WriteLine("Chromium WebRTC bridge ready · WebView2 " + CoreWebView2Environment.GetAvailableBrowserVersionString());
                }
                catch (Exception ex)
                {
                    ready.TrySetException(new InvalidOperationException(
                        "Could not initialize WebView2. Install/update Microsoft Edge WebView2 Runtime.", ex));
                    try { form.Close(); } catch { }
                }
            };

            Application.Run(form);
        }
        catch (Exception ex)
        {
            ready.TrySetException(ex);
        }
    }

    void OnWebMessageReceived(object? sender, CoreWebView2WebMessageReceivedEventArgs e)
    {
        try
        {
            var json = e.TryGetWebMessageAsString();
            using var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;

            if (root.TryGetProperty("event", out var eventProp))
            {
                var name = eventProp.GetString() ?? "event";
                var value = root.TryGetProperty("value", out var valueProp) ? valueProp.GetString() ?? "" : "";
                Console.WriteLine($"Codex Chromium WebRTC {name}: {value}");
                return;
            }

            if (!root.TryGetProperty("id", out var idProp) || !idProp.TryGetInt64(out var id)) return;
            if (!pending.TryRemove(id, out var waiter)) return;

            var ok = root.TryGetProperty("ok", out var okProp) && okProp.GetBoolean();
            if (ok)
            {
                var result = root.TryGetProperty("result", out var resultProp) ? resultProp.GetString() ?? "" : "";
                waiter.TrySetResult(result);
            }
            else
            {
                var error = root.TryGetProperty("error", out var errorProp) ? errorProp.GetString() ?? "Chromium WebRTC command failed." : "Chromium WebRTC command failed.";
                waiter.TrySetException(new InvalidOperationException(error));
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("Chromium WebRTC bridge message error: " + ex.Message);
        }
    }

    async Task<string> InvokeAsync(string command, string? argument = null)
    {
        ThrowIfDisposed();
        await EnsureHostAsync();
        var view = webView ?? throw new InvalidOperationException("WebView2 is not initialized.");
        var id = Interlocked.Increment(ref requestId);
        var waiter = new TaskCompletionSource<string>(TaskCreationOptions.RunContinuationsAsynchronously);
        pending[id] = waiter;

        var script = argument is null
            ? $"window.codexPeer.{command}({id});"
            : $"window.codexPeer.{command}({id}, {JsonSerializer.Serialize(argument)});";

        try
        {
            var dispatch = new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);
            view.BeginInvoke(new Action(async () =>
            {
                try
                {
                    await view.CoreWebView2.ExecuteScriptAsync(script);
                    dispatch.TrySetResult(true);
                }
                catch (Exception ex) { dispatch.TrySetException(ex); }
            }));
            await dispatch.Task.WaitAsync(TimeSpan.FromSeconds(5));
            return await waiter.Task.WaitAsync(TimeSpan.FromSeconds(15));
        }
        finally
        {
            pending.TryRemove(id, out _);
        }
    }

    void ThrowIfDisposed()
    {
        if (disposed) throw new ObjectDisposedException(nameof(CodexOAuthWebRtcPeer));
    }

    public void Dispose()
    {
        if (disposed) return;
        disposed = true;

        foreach (var waiter in pending.Values)
            waiter.TrySetCanceled();
        pending.Clear();

        var form = hostForm;
        if (form is not null && !form.IsDisposed)
        {
            try { form.BeginInvoke(new Action(() => form.Close())); } catch { }
        }
    }
}
